config/routes.rb
FlatRent::Application.routes.draw do
  resources :photos

  resources :offers

  get 'users/ranking'
  resources :events do
    collection do
         get :likeit
     end
  end

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  mount Commontator::Engine => '/commontator'
end

app/models/event.rb
class Event < ActiveRecord::Base
	acts_as_commontable
#	mount_uploader :picture, PictureUploader
	belongs_to :user, counter_cache: true
	acts_as_votable
	has_many :photos
	accepts_nested_attributes_for :photos
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @@event = Event.find params[:id]
    @comments = @event.comments([:draft, :published])
    @photos = @event.photos.all
  end

  # GET /events/new
  def new
    @event = Event.new
    @photo = @event.photos.build
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id 
    respond_to do |format|
      if @event.save
        if params[:photos]
          params[:photos]['photo'].each do |a|
            @photo = @event.photos.create!(:photo => a, :event_id => @event.id)
          end
        end
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        if params[:photos]
          params[:photos]['photo'].each do |a|
            @photo = @event.photos.create!(:photo => a, :event_id => @event.id)
          end
        end
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  def likeit
    @@event.liked_by current_user
    redirect_to @@event
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :picture, :start_date, :start_time, :end_time, :location, :user_id, :city, photos_attributes: [:id, :event_id, :photo])
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>
  <%= f.error_notification %>

  <div class="form-group"> 
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :start_date %>
    <%= f.input :start_time %>
    <%= f.input :end_time %>
    <%= f.input :location %>
    <%= f.input :city %>
    <%= f.hidden_field :user_id %> 
  </div>

  
  <%= f.fields_for :photo do |p| %>
     <div class="field">
       <%= p.label :photo %><br>
       <%= p.file_field :photo, :multiple => true, name: "photos[photo][]" %>
     </div>
   <% end %>

   <% if params[:action] == "edit" %> 
     <% @event.photos.each do |p| %>
       <%= image_tag p.photo, :size => "150x150" %>
       <%= link_to "Destroy", p, method: :delete %>
     <% end %>
   <% end %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<head> 
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" /> 
  <title>Google Maps Multiple Markers</title> 
  <script src="http://maps.google.com/maps/api/js?sensor=false" 
          type="text/javascript"></script>
</head>

<h1>Listing events</h1>

<style>
    td, th {
        padding: 10px;
    }
</style>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th style="width: 30%">Description</th>
      <th>Picture</th>
      <th>Start date</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Location</th>
      <th>City</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.description %></td>
        <td><%= image_tag(event.picture_url, :width => 50) if event.picture.present? %></td>
        <td><%= event.location %></td>
        <td><%= event.city %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) if event.user_id == current_user.id %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } if event.user_id == current_user.id%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>
<div id="map" style="width: 500px; height: 400px;"></div>

  <script type="text/javascript">

  geocoder = new google.maps.Geocoder();
  var locations = [];
  <% @events.each do |event| %>
    var address = '<%= event.city  %>' + '<%= event.location %>';
    locations.push['<%= event.description %>',   geocoder.geocode( { 'address': address}, function(results, status) {
      if (status == google.maps.GeocoderStatus.OK) {
        map.setCenter(results[0].geometry.location);
        var marker = new google.maps.Marker({
            map: map,
            position: results[0].geometry.location
        });
      } else {
        alert('Geocode was not successful for the following reason: ' + status);
      }
    })]
  <% end %>
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 8,
      center: new google.maps.LatLng(-34.397, 150.644),
      mapTypeId: google.maps.MapTypeId.ROADMAP
    });

    var infowindow = new google.maps.InfoWindow();

    var marker, i;

    for (i = 0; i < locations.length; i++) {  
      marker = new google.maps.Marker({
        position: new google.maps.LatLng(locations[i][1], locations[i][2]),
        map: map
      });

      google.maps.event.addListener(marker, 'click', (function(marker, i) {
        return function() {
          infowindow.setContent(locations[i][0]);
          infowindow.open(map, marker);
        }
      })(marker, i));
    }
  </script>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <title>Geocoding service</title>
    <style>
       #map-canvas {
        height: 500px;
        width: 600px;
        margin: 0px;
        padding: 0px
      }
      #panel {
        position: absolute;
        top: 5px;
        left: 700%;
        margin-left: -180px;
        z-index: 5;
        background-color: #fff;
        padding: 5px;
        border: 1px solid #999;
      }
    </style>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
  </head>

<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@event.picture_url, :width => 600) if @event.picture.present? %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @event.start_date %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @event.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @event.end_time %>
</p>

<p>
  <strong>Adress:</strong>
  <%= @event.location %>
</p>
<p>
  <strong>City:</strong>
  <%= @event.city%>
</p>
<p>
  <strong>Likes:</strong>
  <%= @event.votes_for.size %>
</p>

<p>  
  <%= link_to "Like it!", likeit_events_path %>
</p>

<%= commontator_thread(@event) %>

<% @photos.each do |p| %>
  <%= image_tag p.photo_url %>
  <br />
<% end %>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

<script>
var geocoder;
var map;
function initialize() {
  geocoder = new google.maps.Geocoder();
  var latlng = new google.maps.LatLng(-34.397, 150.644);
  var mapOptions = {
    zoom: 15,
    center: latlng
  }
  map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
    var address = '<%= @event.city  %>' + '<%= @event.location %>';
  geocoder.geocode( { 'address': address}, function(results, status) {
    if (status == google.maps.GeocoderStatus.OK) {
      map.setCenter(results[0].geometry.location);
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });
    } else {
      alert('Geocode was not successful for the following reason: ' + status);
    }
  });

}

function codeAddress() {
  var address = '<%= @event.city  %>' + '<%= @event.location %>';
  geocoder.geocode( { 'address': address}, function(results, status) {
    if (status == google.maps.GeocoderStatus.OK) {
      map.setCenter(results[0].geometry.location);
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });
    } else {
      alert('Geocode was not successful for the following reason: ' + status);
    }
  });
}
google.maps.event.addDomListener(window, 'load', initialize);
</script>
<div id="map-canvas"></div>