config/routes.rb
FlatRent::Application.routes.draw do
  resources :photos

  resources :offers

  get 'users/ranking'
  resources :events do
    collection do
         get :likeit
     end
  end

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  mount Commontator::Engine => '/commontator'
end

app/models/offer.rb
class Offer < ActiveRecord::Base
	 belongs_to :user, counter_cache: true
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.all
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(offer_params)
    @offer.user_id = current_user.id 

    respond_to do |format|
      if @offer.save
        format.html { redirect_to @offer, notice: 'Offer was successfully created.' }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params.require(:offer).permit(:title, :cost, :picture, :start_date, :end_date, :area, :rooms, :localization, :description)
    end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.erb
<%= simple_form_for(@offer) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :cost %>
    <%= f.input :picture %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <%= f.input :area %>
    <%= f.input :rooms %>
    <%= f.input :localization %>
    <%= f.input :description %>
    <%= f.hidden_field :user_id %> 
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/offers/edit.html.erb
<h1>Editing offer</h1>

<%= render 'form' %>

<%= link_to 'Show', @offer %> |
<%= link_to 'Back', offers_path %>

app/views/offers/index.html.erb
<h1>Listing offers</h1>

<style>
    td, th {
        padding: 10px;
    }
</style>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Cost</th>
      <th>Picture</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Area</th>
      <th>Rooms</th>
      <th>Localization</th>
      <th style="width: 30%">Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offers.each do |offer| %>
      <tr>
        <td><%= offer.title %></td>
        <td><%= offer.cost %></td>
        <td><%= offer.picture %></td>
        <td><%= offer.start_date %></td>
        <td><%= offer.end_date %></td>
        <td><%= offer.area %></td>
        <td><%= offer.rooms %></td>
        <td><%= offer.localization %></td>
        <td><%= offer.description %></td>
        <td><%= link_to 'Show', offer %></td>
        <td><%= link_to 'Edit', edit_offer_path(offer) if offer.user_id == current_user.id %></td>
        <td><%= link_to 'Destroy', offer, method: :delete, data: { confirm: 'Are you sure?' } if offer.user_id == current_user.id%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Offer', new_offer_path %>

app/views/offers/new.html.erb
<h1>New offer</h1>

<%= render 'form' %>

<%= link_to 'Back', offers_path %>

app/views/offers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @offer.title %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @offer.cost %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @offer.picture %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @offer.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @offer.end_date %>
</p>

<p>
  <strong>Area:</strong>
  <%= @offer.area %>
</p>

<p>
  <strong>Rooms:</strong>
  <%= @offer.rooms %>
</p>

<p>
  <strong>Localization:</strong>
  <%= @offer.localization %>
</p>

<p>
  <strong>Description:</strong>
  <%= @offer.description %>
</p>

<%= link_to 'Edit', edit_offer_path(@offer) %> |
<%= link_to 'Back', offers_path %>