config/routes.rb
FlatRent::Application.routes.draw do
  resources :photos

  resources :offers

  get 'users/ranking'
  resources :events do
    collection do
         get :likeit
     end
  end

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users

  mount Commontator::Engine => '/commontator'
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <p class="navbar-text pull-right">
          <% if user_signed_in? %>
            <li><%= link_to 'Edit account', edit_user_registration_path %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
          <% else %>
            <li><%= link_to 'Login', new_user_session_path %></li>
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
            
        <% end %></p>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
  <li><%= link_to 'Events', events_path %></li>
  <li><%= link_to 'Offers', offers_path %></li>
  <li><%= link_to 'Ranking', users_ranking_path %></li>
  <li><%= image_tag(current_user.avatar_url, width:50)%></li>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Flat Rent" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Flat Rent" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>